apiVersion: v1
name: python-helloworld-v2.0.0 
description: Install a Python HelloWorld deployment
keywords:
- python
- helloworld 
version: 1.0.0
maintainers:
- name: Ayman Hamouda 
  email: ayman.hamouda@live.com
