# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ${{matrix.os}}
    runs-on : ubuntu-latest
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macOs-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - 
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: aymanhamouda/python-helloworld # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
     
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v1.2.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.ref == 'refs/heads/test'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    platforms: linux/amd64
      #    push: true
      #    tags: aymanhamouda/python-helloworld:latest
      -
        name: Build and push
        id: docker_build
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - name: Check out the repo
     #   uses: actions/checkout@v2


      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aymanhamouda/python-helloworld
          tag_with_ref: true
