apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld-v2.0.0
  name: python-helloworld-v2.0.0
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: python-helloworld-v2.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld-v2.0.0
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent 
        name: python-helloworld-v2.0.0
